In [15]:
import numpy as np
import pandas as pd
np.set_printoptions(formatter={'float': lambda x: "{0:0.1f}".format(x)})

Reading Data

In [24]:
dataSet = pd.read_csv('Data.csv')
X = dataSet.iloc[:,0:3].values
Y = dataSet.iloc[:,-1].values

print("feature Matrix/Independent Variables\n",X)
print("Dependent Variables\n",Y)


feature Matrix/Independent Variables
 [['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]
Dependent Variables
 ['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


# Fill missing data

In [25]:
from sklearn.preprocessing import Imputer

imputer = Imputer(missing_values = 'NaN', strategy = 'mean', axis = 0)
imputer = imputer.fit(X[:, 1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3])

# Enoding the Categorial Data

Machine Learning models are based on mathematical values, so it will create problem working with non-numerical values.

Countries column(0) has 3 category of countries so we will encode that into number.

In [26]:
print(X[:,0])

['France' 'Spain' 'Germany' 'Spain' 'Germany' 'France' 'Spain' 'France'
 'Germany' 'France']


In [27]:
from sklearn.preprocessing import LabelEncoder

labelencoder_X = LabelEncoder()
X[:, 0] = labelencoder_X.fit_transform(X[:, 0])
print(X[:,0])

[0 2 1 2 1 0 2 0 1 0]


Okay... So we have encoded countries into numbers but it has one problem i.e ML algo will learn these values and try to relate these numbers (2>1>0) which doesnt make any sense here(i.e for countries). Suppose if we had categories as(large,small,medium) then it make sense to have numbers for these.

Fix : we can have 3 columns for these 3 categories

In [28]:
from sklearn.preprocessing import OneHotEncoder
X = OneHotEncoder(categorical_features = [0]).fit_transform(X).toarray()

So now we have three columns in order to identify a category.

In [29]:
print(X)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.8]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.8 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [22]:
labelencoder_Y = LabelEncoder()
Y = labelencoder_X.fit_transform(Y)